name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: setup
      run: sudo apt-get update;
           sudo apt-get install libsdl2-dev libsdl2-ttf-dev
    - name: configure (debug)
      run: ./configure debug
    - name: make (debug)
      run: make -j 2
    - name: test
      run: ./test.sh
    - name: configure (release)
      run: ./configure release
    - name: make (release)
      run: make -j 2
